Section "Device"
    Identifier "fb"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection
Section "Screen"
    Identifier "s0"
    Device "fb"
EndSection
Section "ServerLayout"
    Identifier "l0"
    Screen "s0"
EndSection
